### ISSUE TITLE
Tier for 3vs3 and 5vs5 (including points)

### ISSUE THREAD

**Issue by monkey239** [zeroclutch/vghours#5]
As now the tier level and related points are available in Vainglory, it would be nice to add that information to your overview

**Comment by zeroclutch** [comment]
Showing tier points could cause a lot of toxicity between users, e.g. "Wow, you spent X hours on the game but you're only tier X?". I'm not trying to encourage this type of tier shaming, so I don't intend on adding this feature to the website.
